// <auto-generated />
namespace EF_Ekzamen_BookStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddtableBookingandForeignKeyBookId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddtableBookingandForeignKeyBookId));
        
        string IMigrationMetadata.Id
        {
            get { return "202302031430095_Add table Booking and ForeignKey BookId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
